export { default as HeroImg } from "./heroImg.png";
export { default as GridAboutImg1 } from "./gridAboutImg1.png";
export { default as Kente1 } from "./kente1.png";
export { default as Kente2 } from "./kente2.png";
export { default as Ayomide } from "./ayomide.png";
export { default as Lola } from "./lola.png";
export { default as Asiedu } from "./asiedu.png";
export { default as Fanta } from "./fanta.png";
export { default as Dami } from "./dami.png";
export { default as Taylor } from "./taylor.png";
export { default as Melody } from "./melody.png";
export { default as Valerio } from "./valerio.png";
export { default as Tiktok } from "./tiktok.svg";
export { default as Instagram } from "./instagram.svg";
export { default as Facebook } from "./facebook.svg";
export { default as Logo } from "./logo.png";
export { default as JoinUsImg } from "./joinUsImg.png";
export { default as NavLogo } from "./navLogo.png";
export { default as GoodMolecules } from "./GoodMolecules-Logo.png";
export { default as  Fenty} from "./Fenty.png";
export { default as Alaffia } from "./alaffia.png";
export { default as  Sol} from "./sol.png";
export { default as  Anas} from "./anastasia.png";
export { default as Mugler } from "./mugler.png";
export { default as  Prada} from "./Prada.png";
export { default as  Faced} from "./faced.png";
export { default as  Dior} from "./dior.png";
export { default as Shea } from "./shea.png";
export { default as Shein } from "./shein.png";
export { default as  Forever} from "./Forever.png";
export { default as  Sienna} from "./Sienna.png";
export { default as Lorvea } from "./lorvae.png";
export { default as  SlideShow} from "./Slideshow.png";
// export { default as  } from ".";
// export { default as  } from ".";
// export { default as  } from ".";
// export { default as  } from ".";
// export { default as  } from ".";